### ISSUE TITLE
Unexpected character error

### ISSUE THREAD

**Issue by MatissJanis** [FidelLimited/serverless-plugin-optimize#19]
Hello,

I'm trying to add this plugin to my codebase, but a error keeps popping up. Have you had this issue before?

```
Error: SyntaxError: Unexpected character '�' while parsing file: /Users/matiss/personal/property-crawler/list-crawler/node_modules/iconv/build/Release/iconv.node (line: 1, col: 0, pos: 0)

Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at parse_error (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1677:9)
    at Object.next_token [as input] (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1949:9)
    at next (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2078:25)
    at Object.parse (eval at <anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2064:15)
    at addFile (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:71:33)
    at /Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:80:17
    at Array.forEach (native)
    at Object.exports.minify (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglify-js/tools/node.js:78:26)
    at Stream.ready (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglifyify/index.js:71:19)
    at Stream.<anonymous> (/Users/matiss/personal/property-crawler/list-crawler/node_modules/uglifyify/index.js:97:12)
    at _end (/Users/matiss/personal/property-crawler/list-crawler/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/matiss/personal/property-crawler/list-crawler/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/matiss/personal/property-crawler/list-crawler/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at endReadableNT (/Users/matiss/personal/property-crawler/list-crawler/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:865:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at module.exports.logError.errorHandlingError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:82:11)
    at BbPromise.resolve.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:20:15)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

Here's my package.json dependencies
```
{
  "dependencies": {
    "aws-sdk": "^2.7.6",
    "babel-preset-es2015": "^6.18.0",
    "crawler": "git://github.com/bda-research/node-crawler.git#1.0.0-beta",
    "q": "^1.4.1",
    "serverless-plugin-optimize": "git://github.com/FidelLimited/serverless-plugin-optimize.git#master"
  },
  "devDependencies": {}
}
```

**Comment by dwolfand** [comment]
I noticed that when trying to use the non default babel preset of es2015 I get similar errors - are you using different babel presets? I'm in the process of trying to troubleshoot this now.

**Comment by MatissJanis** [comment]
No, I have no customisations for this plugin. Essentially this is all my `serverless.yml` file.

```
service: mja-name

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true

functions:
  name:
    handler:  handler.myHandler
plugins:
  - serverless-plugin-optimize

package:
  individually: true
```

**Comment by dwolfand** [comment]
I have a feeling this is related to uglify not supporting ES6, see [here](https://github.com/mishoo/UglifyJS2/issues/448)

**Comment by cryptoquick** [comment]
I have minify set to false, and it's still hitting this error. For me, it's due to a `.node` binary file being required in a package, the one I'm using is called `sharp`.

**Comment by goncaloneves** [comment]
@dwolfand Check if the problem is due to global was not being set in babelify. PR #14 solved this and I just published it now to npm.

@cryptoquick I will be including browserify options `extensions` array that you will be able to add other extensions besides `.js` and `.json`.

**Comment by goncaloneves** [comment]
@dwolfand @cryptoquick new release should solve all these issues.

**Comment by dionysio** [comment]
This one still happens to me with the sharp module. I have tried setting ignore to the .node file but it did not help. Setting minify to false changes the output to:

`Unexpected character ''`

with no additional traceback info - I have tried setting SLS_DEBUG and debug as well and nothing more shows up.

**Comment by goncaloneves** [comment]
That happens during optimization?

Test manually Browserify on your file from CLI. And see if it bundles well.

Make sure you go through all Browserify, Babel options correctly.

I can only help if you point that the cause is from the plugin.

**Comment by dionysio** [comment]
Yea, so it seems it has more to do with browserify & those node packages that have C++ addons (like sharp) than your plugin. Also with the sharp it probably does not make that much difference to bundle the js as the libs themselves are over 20mb...

**Comment by cryptoquick** [comment]
dionysio, I fixed the sharp issue on my end. it doesn't involve this plugin, however, and I don't think it would work even if browserify could bundle `.node` files. It wouldn't also provide the requisite lib / .so files, and it wouldn't be built for the AWS lambda architecture, it'd be built for your own local architecture. I wound up creating a set of shell scripts & npm run scripts that uses stock Babel CLI to build your code, scp it to a build server running an Amazon Linux image as described in the [Sharp documentation](http://sharp.dimens.io/en/stable/install/#aws-lambda) that builds sharp, then I remotely run a shell script on that server to build it, remove unnecessary folders, and zip the project. Then I pull it back down via scp and deploy that with serverless. The whole deployment process takes about five minutes.

**Comment by cryptoquick** [comment]
I should add that this is not a bad solution if you also want to use sharp-blockhash and you're using a lambda services architecture, so you don't deploy these things very often, once built. Though, it only works well enough if you use the fork of the repo I have on my profile. For some reason the latest sharp wouldn't work with the older code, I think it was an issue with how blockhash manages prototypal configuration data. But regardless, we're out in the weeds, and that's not that relevant to this issue.

**Comment by hoonoh** [comment]
browserify external feature seems to work for this kind of situation #34
