### ISSUE TITLE
module.require is not a function

### ISSUE THREAD

**Issue by jasonlimantoro** [FidelLimited/serverless-plugin-optimize#83]
Without the plugin, the deployed functions work well.
However, after enabling the plugin, although it's significantly smaller, invoking the API yields the error `module.require is not a function`, yielding 5xx HTTP status code.

Any ideas?

**Comment by luaneyed** [comment]
I got same error.
In my case, it was resolved after matching serverless runtime (which was node 8) with local runtime (node 10).

But I can't say it's just runtime problem with confidence, because executing the result of `sls package` in local made same error.

**Comment by montamal** [comment]
Still a problem even with matching runtime versions, it plays badly with some modules. In my case it was apollo-server-lambda@2.10, reported the issue to them but turns out it was this plugin.

This is worth looking into.

**Comment by juanpujol** [comment]
Have the same issue with apollo-server-lambda@2.16.1 the package is huge w/o serverless-plugin-optimize

**Comment by gastonrey** [comment]
Hi, any news on this? Anyone got it working at some point? Am getting `"errorMessage": "require.resolve is not a function"` error and it's probably related.
